student_count = 22

puts "The students of my cohort at Makers Academy"
puts "test1"
puts "test2 test"
puts "Faisal Aydarus"
puts "mayadrivermd"
puts "michballard"
puts "henry stanley" 
puts "jerome.pratt" 
puts "chris oatley"
puts "ilccyk"
puts "leo poldkwok"
puts "tillett"
puts "nickrhys"
puts "james.r.mcneil" 
puts "lovis-schultze"
puts "tatienantes"
puts "iblockchain" 
puts "v.koch"
puts "byverdu" 
puts "dave wickes"
puts "silver io funk" 
puts "andy gates010" 
puts "spike01"
puts "global avocado" 
puts "mr. yogesh"

print "Overall, we have #{student_count} great students "
